"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from config.env import BASE_DIR, env

env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = ['*']

# Auth User Model Config
AUTH_USER_MODEL = 'members.Member'
PHONENUMBER_DEFAULT_REGION = 'DZ'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'single_session',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'handlers',
    'allauth',
    'allauth.account',
    'checkouts',
    'pages',
    'search',
    'authentication',
    'settings',

    'django_htmx',
    'alerts',

    'members',
    'accounts',
    'recaptcha',
    'wallets',
    'currencies',
    'balances',
    'transactions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',

    'django_htmx.middleware.HtmxMiddleware',
    'alerts.middleware.AlertMessagesMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en'
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

TIME_ZONE = 'Africa/Algiers'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'config/static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles-cdn')

# media files (Images)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# COOKIES & SESSIONS

CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False

SINGLE_USER_SESSION = True
LOGOUT_ALL_SESSIONS = True

CSRF_FAILURE_VIEW = 'handlers.views.csrf_handler403_view'

# Email config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'erdeem.sca@gmail.com'


# allauth config
ACCOUNT_ADAPTER = 'accounts.adapter.AccountAdapter'
TEMPLATE_EXTENSION = 'html'
EMAIL_SUBJECT_PREFIX = 'Erdeem'

AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
]

ACCOUNT_FORMS = {
    'signup': 'registrations.forms.RegistrationForm',
    'login': 'registrations.forms.AuthenticationForm'
}

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_CHANGE_EMAIL = False
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = False


# URL Configuration
from django.urls import reverse_lazy

LOGIN_URL = reverse_lazy('account_login')
LOGIN_REDIRECT_URL = reverse_lazy('pages:home')
LOGOUT_REDIRECT_URL = LOGIN_URL
ACCOUNT_SIGNUP_REDIRECT_URL = LOGIN_REDIRECT_URL


# reCAPTCHA
RECAPTCHA_PUBLIC_KEY = env('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY =  env('RECAPTCHA_PRIVATE_KEY')
RECAPTCHA_REQUIRED_SCORE = 0.6


# Search Engine Config
SEARCH_CATEGORIES_MAPPING = {}


# Chargily Payment Gateway
CHARGILY_URL = env('CHARGILY_URL')
CHARGILY_KEY = env('CHARGILY_KEY')
CHARGILY_SECRET = env('CHARGILY_SECRET')
CHARGILY_DEFAULT_PAYMENT_CURRENCY = 'dzd'


# Binance config
BINANCE_API_KEY = 'your_api_key_here'
BINANCE_SECRET_KEY = 'your_secret_key_here'


# Erdeem config
ERDEEM_MERCHANT_ID = env.int('ERDEEM_MERCHANT_ID')
from decimal import Decimal
MIN_TRANSACTION_AMOUNT_IN_USD = Decimal(5.00) # Min transaction amount: 5.00$