# Generated by Django 4.2 on 2024-06-23 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargily_entity_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_currency', models.CharField(choices=[('dzd', 'DZD')], max_length=3, verbose_name='Currency')),
                ('payment_method', models.CharField(choices=[('edahabia', 'Edahabia'), ('cib', 'CIB')], default='edahabia', max_length=10)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('checkout_url', models.URLField()),
                ('quantity', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(limit_value=5, message='Quantity must be at least 5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
