# Generated by Django 4.2 on 2024-06-23 14:33

import currencies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('chargily_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default=currencies.models.Currency.default_directory_path, upload_to=currencies.models.Currency.directory_path)),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Exchange Rate To USD')),
                ('exchange_rate_to_dzd', models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Exchange Rate To DZD')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
    ]
