# Generated by Django 4.2 on 2024-06-23 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transactions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigIntegerField(db_index=True, default=transactions.utils.set_unique_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('in_progress', 'In Progress'), ('refunded', 'Refunded'), ('on_hold', 'On Hold'), ('disputed', 'Disputed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('exchange', 'Exchange'), ('transfer', 'Transfer'), ('trade', 'Trade')], max_length=20)),
                ('payment_method', models.CharField(choices=[('chargily', 'Chargily'), ('paypal', 'PayPal'), ('google_pay', 'Google Pay'), ('redotpay', 'Redotpay')], default='chargily', max_length=20, null=True)),
                ('withdrawal_destination', models.CharField(choices=[('edahabia', 'Edahabia'), ('cib', 'CIB'), ('paypal', 'PayPal'), ('redotpay', 'Redotpay')], default='edahabia', max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, default=transactions.utils.set_unique_slug, unique=True)),
                ('balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='balances.balance')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_transactions', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['merchant', 'recipient', 'created_at'], name='transaction_merchan_25f107_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'transaction_type'], name='transaction_status_bef12d_idx'),
        ),
    ]
