# Generated by Django 4.2 on 2024-06-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='wallet',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='wallets.wallet'),
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['amount'], name='balances_ba_amount_e0d719_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('wallet', 'currency')},
        ),
    ]
